### ISSUE TITLE
Fix issue regarding relative values query removing fieldCategory filter

### ISSUE THREAD

**Issue by avlisodraude** [CLARIAH/wp5_mediasuite#469] opened 2018-07-11 14:22 UTC
Currently the query to get the relative values is removing the fieldCategory field (setting it to []) which causes in some queries to get in the 'unfiltered' resultset more hits than with the original query.
Because of this (in some cases) we get 'relative' values greater than 100% as in the next screenshot:

![Screen Shot 2018-07-11 at 16.17.14.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/c989e554-a2e5-45a8-800a-430e29629478)

The source of this issue is in the QueryComparisonLineChart.jsx (L:116) when setting the fieldCategory to [] before sending the query.

**Comment by lilimelgar** [comment] 2018-07-18 11:15
@avlisodraude: I tested the branch "task/#469-fixing-relative-values-chart". The issue is fixed for B&G collection, but the problem persists with other collections, e.g.,: 

Desmet papers:
![screen shot 2018-07-18 at 13 08 06](https://user-images.githubusercontent.com/8133228/42878001-d1287342-8a8b-11e8-86c4-c263217bcc99.png)

Radio collection B&G:
![screen shot 2018-07-18 at 13 15 07](https://user-images.githubusercontent.com/8133228/42878255-a9da0282-8a8c-11e8-9729-a20f68938b1e.png)

**Comment by jblom** [comment] 2018-07-25 11:20
this should be fixed now on test/master

**Comment by lilimelgar** [comment] 2018-08-14 11:39
Yes, tested on Master with several collections, alles Ok

**Closed by lilimelgar** 2018-08-14 11:39 UTC
Labels: bug
